import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import 'react-big-calendar/lib/css/react-big-calendar.css'
import "./globals.css";

import { ToastContainer,  } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
         
          {children}
        </ThemeProvider>
        <ToastContainer theme="colored" />
        

      </body>
    </html>
  );
}
